import type { Category } from './types';

export const KAOMOJI_CATEGORIES: Category[] = [
  {
    "name": "Happy",
    "kaomojis": [
      { "emoji": "(^o^)", "tags": ["happy", "joy", "smile"] },
      { "emoji": "(^.^)", "tags": ["happy", "smile", "cheerful"] },
      { "emoji": "(⌒▽⌒)", "tags": ["happy", "joyful", "delighted"] },
      { "emoji": "(*^▽^*)", "tags": ["happy", "excited", "gleeful"] },
      { "emoji": "(o^▽^o)", "tags": ["happy", "elated", "thrilled"] },
      { "emoji": "٩(◕‿◕｡)۶", "tags": ["happy", "excited", "celebrating"] },
      { "emoji": "ヽ(・∀・)ﾉ", "tags": ["happy", "waving", "greeting"] },
      { "emoji": "(´｡• ᵕ •｡`)", "tags": ["happy", "blushing", "content"] },
      { "emoji": "(*¯︶¯*)", "tags": ["happy", "satisfied", "pleased"] },
      { "emoji": "(´∀`)", "tags": ["happy", "laughing", "amused"] },
      { "emoji": "＼(￣▽￣)／", "tags": ["happy", "cheering", "triumphant"] },
      { "emoji": "╰(▔∀▔)╯", "tags": ["happy", "joyful", "victorious"] },
      { "emoji": "(•_•) ( •_•)>⌐■-■ (⌐■_■)", "tags": ["cool", "deal with it", "sunglasses"] },
      { "emoji": "c(ˊ･ G ･`)> *whistle*", "tags": ["whistling", "casual", "happy"] },
      { "emoji": "(๑>ᴗ<๑)", "tags": ["excited", "happy", "cute"] },
      { "emoji": "(o´▽`o)", "tags": ["happy", "delighted", "glad"] },
      { "emoji": "(☆ω☆)", "tags": ["happy", "starry-eyed", "impressed"] },
      { "emoji": "｡ﾟ( ﾟ^∀^ﾟ)ﾟ｡", "tags": ["happy", "laughing", "tears of joy"] },
      { "emoji": "( ´ ▽ ` )", "tags": ["happy", "content", "relaxed"] },
      { "emoji": "٩(ˊᗜˋ*)و", "tags": ["happy", "excited", "energetic"] },
      { "emoji": "(*≧ω≦)", "tags": ["overjoyed", "happy", "ecstatic"] },
      { "emoji": "(*^‿^*)", "tags": ["happy", "smile", "joyful"] },
      { "emoji": "☆*:.｡.o(≧▽≦)o.｡.:*☆", "tags": ["very happy", "sparkling", "excited"] },
      { "emoji": "v(o´∀`o)v", "tags": ["happy", "peace sign", "victory"] },
      { "emoji": "(b^v^)b", "tags": ["happy", "thumbs up", "good"] },
      { "emoji": "\\(^o^)／", "tags": ["cheering", "happy", "hooray"] },
      { "emoji": "(*´∀`*)", "tags": ["happy", "content", "blissful"] },
      { "emoji": "(๑´ㅂ`๑)", "tags": ["happy", "cute", "pleased"] },
      { "emoji": "(((o(*ﾟ▽ﾟ*)o)))", "tags": ["very excited", "happy", "thrilled"] },
      { "emoji": "(*˘︶˘*).｡.:*♡", "tags": ["happy", "dreamy", "lovely", "content"] },
      { "emoji": "룰루♪", "tags": ["happy", "singing", "korean"] },
      { "emoji": "⁽⁽◝( •௰• )◜⁾⁾", "tags": ["dancing", "happy", "joyful"] },
      { "emoji": "(ﾉ´ヮ`)ﾉ*:･ﾟ✧", "tags": ["happy", "excited", "magic", "sparkles"] }
    ]
  },
  {
    "name": "Sad",
    "kaomojis": [
      { "emoji": "(T_T)", "tags": ["sad", "crying", "tears"] },
      { "emoji": "(/_T)", "tags": ["sad", "crying", "depressed"] },
      { "emoji": "(;_;)", "tags": ["sad", "crying", "weeping"] },
      { "emoji": "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡", "tags": ["sad", "sobbing", "bawling"] },
      { "emoji": "(´;ω;`)", "tags": ["sad", "whimpering", "miserable"] },
      { "emoji": "(╯︵╰,)", "tags": ["sad", "pouting", "disappointed"] },
      { "emoji": "(-_-)", "tags": ["sad", "annoyed", "unimpressed"] },
      { "emoji": "(ಥ_ಥ)", "tags": ["sad", "crying", "emotional"] },
      { "emoji": "(; ω ;)", "tags": ["sad", "teary", "upset"] },
      { "emoji": "o(TヘTo)", "tags": ["sad", "depressed", "dismay"] },
      { "emoji": "┐('～`;)┌", "tags": ["shrug", "dunno", "sad"] },
      { "emoji": "(μ_μ)", "tags": ["sad", "sleepy", "down"] },
      { "emoji": "(ノ_<。)", "tags": ["sad", "crying", "hurt"] },
      { "emoji": "（；へ：）", "tags": ["sad", "whining", "disappointed"] },
      { "emoji": "(´-ω-`)", "tags": ["sad", "displeased", "sigh"] },
      { "emoji": "(._.)", "tags": ["sad", "depressed", "looking down"] },
      { "emoji": "(´•̥ ω •̥` )", "tags": ["sad", "crying", "tears"] },
      { "emoji": "(╥_╥)", "tags": ["sad", "crying", "sobbing"] },
      { "emoji": "｡･ﾟﾟ･(>д<)･ﾟﾟ･｡", "tags": ["sad", "crying loudly", "wailing"] },
      { "emoji": "(´･ω･`)", "tags": ["sad", "dejected", "shobon"] },
      { "emoji": "(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)", "tags": ["crying a lot", "sobbing", "very sad"] },
      { "emoji": "(；ω；)", "tags": ["crying", "sad", "tears"] },
      { "emoji": "（´＿｀）", "tags": ["sigh", "dejected", "sad"] },
      { "emoji": "(Ｔ▽Ｔ)", "tags": ["crying", "sad", "tears"] },
      { "emoji": "..・ヾ(。＞＜)シ", "tags": ["crying", "waving goodbye", "sad"] },
      { "emoji": "p(･･,*)", "tags": ["crying", "sad", "tears"] },
      { "emoji": "（Ω Д Ω）", "tags": ["sobbing", "crying loudly", "sad"] },
      { "emoji": "orz", "tags": ["despair", "kneeling", "disappointed", "sad"] },
      { "emoji": "OTL", "tags": ["despair", "kneeling", "disappointed", "sad"] },
      { "emoji": "_(´ཀ`」 ∠)_", "tags": ["dead", "exhausted", "sad"] },
      { "emoji": "இдஇ", "tags": ["crying", "sad", "tears"] },
      { "emoji": "(´Д｀。)", "tags": ["sad", "depressed", "sigh"] },
      { "emoji": "(´ A `)", "tags": ["sad", "disappointed", "dejected"] }
    ]
  },
  {
    "name": "Angry",
    "kaomojis": [
      { "emoji": "(>_<)", "tags": ["angry", "frustrated", "mad"] },
      { "emoji": "(-_-#)", "tags": ["angry", "annoyed", "ticked off"] },
      { "emoji": "(╯°□°）╯︵ ┻━┻", "tags": ["angry", "table flip", "rage"] },
      { "emoji": "((o(-_-)o))", "tags": ["angry", "fuming", "irritated"] },
      { "emoji": "(`A´)", "tags": ["angry", "yelling", "shouting"] },
      { "emoji": "(╬ Ò ‸ Ó)", "tags": ["angry", "furious", "enraged"] },
      { "emoji": "٩(ఠ益ఠ)۶", "tags": ["angry", "demon", "rage"] },
      { "emoji": "p(＃^.)", "tags": ["angry", "punching", "fighting"] },
      { "emoji": "t(-_-t)", "tags": ["angry", "flipping off", "insult"] },
      { "emoji": "(＃`Д´)", "tags": ["angry", "mad", "upset"] },
      { "emoji": "ヽ(｀Д´#)ﾉ", "tags": ["angry", "furious", "outraged"] },
      { "emoji": "ლ(ಠ益ಠლ)", "tags": ["angry", "why", "frustrated"] },
      { "emoji": "凸( ` ﾛ ´ )凸", "tags": ["angry", "flipping off", "rude"] },
      { "emoji": "(ノಠ益ಠ)ノ彡┻━┻", "tags": ["angry", "table flip", "rage"] },
      { "emoji": "୧( ಠ Д ಠ )୨", "tags": ["angry", "menacing", "fist"] },
      { "emoji": "(凸ಠ益ಠ)凸", "tags": ["angry", "flipping off", "rage"] },
      { "emoji": "(┛◉Д◉)┛彡┻━┻", "tags": ["angry", "table flip", "intense"] },
      { "emoji": "(#ﾟДﾟ)", "tags": ["angry", "shouting", "mad"] },
      { "emoji": "(お`ω´)o", "tags": ["angry", "punch", "fight"] },
      { "emoji": "٩(ŏ﹏ŏ、)۶", "tags": ["angry", "frustrated", "upset"] },
      { "emoji": "ヽ( #`Д´)ﾉ", "tags": ["angry", "furious", "outraged"] },
      { "emoji": "(＃`皿´)", "tags": ["grinding teeth", "angry", "furious"] },
      { "emoji": "ψ(▼へ▼メ)～→", "tags": ["angry", "devil", "spear", "menacing"] },
      { "emoji": "(╬`益´)", "tags": ["angry", "vein pop", "furious"] },
      { "emoji": "(〃＞目＜)", "tags": ["angry", "frustrated", "annoyed"] },
      { "emoji": "ヽ( `д´*)ノ", "tags": ["angry", "stomping", "mad"] },
      { "emoji": "(`Д´)ノ", "tags": ["angry", "shouting", "mad"] },
      { "emoji": "凸( `ー´)凸", "tags": ["flipping off", "rude", "angry"] },
      { "emoji": "ヾ(｀ヘ´)ﾉﾞ", "tags": ["angry", "furious", "pissed"] },
      { "emoji": "[○･｀Д´･○]", "tags": ["angry", "yelling", "mad"] },
      { "emoji": "٩(╬ʘ益ʘ╬)۶", "tags": ["rage", "furious", "angry"] },
      { "emoji": "(#`O′)o", "tags": ["angry", "punch", "mad"] },
      { "emoji": "(‡▼益▼)", "tags": ["angry", "evil", "mad"] }
    ]
  },
  {
    "name": "Love",
    "kaomojis": [
      { "emoji": "(´｡• ᵕ •｡`) ♡", "tags": ["love", "blushing", "heart"] },
      { "emoji": "(*♡∀♡)", "tags": ["love", "in love", "crush"] },
      { "emoji": "(｡♥‿♥｡)", "tags": ["love", "heart eyes", "affection"] },
      { "emoji": "(*^3^)/~☆", "tags": ["love", "kiss", "blowing kiss"] },
      { "emoji": "(づ￣ ³￣)づ", "tags": ["love", "hug", "kiss"] },
      { "emoji": "♡( ◡‿◡ )", "tags": ["love", "content", "serene"] },
      { "emoji": "(/▽＼*)｡o○♡", "tags": ["love", "shy", "blushing"] },
      { "emoji": "Σ>―(〃°ω°〃)♡→", "tags": ["love", "cupid", "arrow"] },
      { "emoji": "(ﾉ´ з `)ノ", "tags": ["love", "blowing kiss", "affection"] },
      { "emoji": "♥(ˆ⌣ˆԅ)", "tags": ["love", "hug", "cuddle"] },
      { "emoji": "(ʃƪ˘³˘)", "tags": ["love", "kiss", "shy"] },
      { "emoji": "(` ω ´)", "tags": ["love", "smug", "affectionate"] },
      { "emoji": "(人-ω◕)", "tags": ["love", "wink", "cute"] },
      { "emoji": "★~(◠ω◕✿)", "tags": ["love", "wink", "cute"] },
      { "emoji": "~(˘▾˘~)", "tags": ["love", "dancing", "happy"] },
      { "emoji": "( ˘ ³˘)♥", "tags": ["love", "kiss", "heart"] },
      { "emoji": "(/ω＼)♡", "tags": ["love", "shy", "blushing"] },
      { "emoji": "(´,,•ω•,,)♡", "tags": ["love", "blushing", "cute"] },
      { "emoji": "I love you ♡", "tags": ["love", "text", "confession"] },
      { "emoji": "(っ˘з(˘⌣˘ )", "tags": ["love", "kissing", "couple"] },
      { "emoji": "(❤ω❤)", "tags": ["love", "heart eyes", "in love"] },
      { "emoji": "chu♥(人´3｀)⌒♡", "tags": ["blowing kiss", "love", "chu"] },
      { "emoji": "♡(｡- ω -)", "tags": ["love", "peaceful", "calm"] },
      { "emoji": "（●´∀｀）ノ♡", "tags": ["love", "waving", "greeting"] },
      { "emoji": "~( ♥ 3 ♥ )~", "tags": ["kiss", "love", "pucker"] },
      { "emoji": "σ(♡∞♡)", "tags": ["in love", "obsessed", "crush"] },
      { "emoji": "φ(♡ . ♡)φ", "tags": ["in love", "dazed", "smitten"] },
      { "emoji": "(*´-`)~♥", "tags": ["love", "sigh", "affectionate"] },
      { "emoji": "(♥´∀｀)／", "tags": ["love", "happy", "affection"] },
      { "emoji": "♡(.◜ω◝.)♡", "tags": ["love", "content", "sweet"] },
      { "emoji": "( ´ ∀ `)ノ～ ♡", "tags": ["love", "blowing kiss", "heart"] },
      { "emoji": "(｡・//ε//・｡)", "tags": ["love", "blushing", "shy"] },
      { "emoji": "♥(´∀` )人", "tags": ["love", "couple", "holding hands"] }
    ]
  },
  {
    "name": "Animals",
    "kaomojis": [
      { "emoji": "(=^･ω･^=)", "tags": ["animal", "cat", "kitty"] },
      { "emoji": "U ´ᴥ` U", "tags": ["animal", "dog", "puppy"] },
      { "emoji": "|(￣3￣)|", "tags": ["animal", "pig", "oink"] },
      { "emoji": "ʕ •ᴥ•ʔ", "tags": ["animal", "bear", "teddy"] },
      { "emoji": "<(o )___", "tags": ["animal", "squid", "sea"] },
      { "emoji": "°)))彡", "tags": ["animal", "fish", "swimming"] },
      { "emoji": "(/) (°,,°) (\\)", "tags": ["animal", "crab", "pincer"] },
      { "emoji": "～>`)～～～", "tags": ["animal", "snake", "hiss"] },
      { "emoji": "(\\_(\\)", "tags": ["animal", "rabbit", "bunny"] },
      { "emoji": "(>'-'<)", "tags": ["animal", "bat", "flying"] },
      { "emoji": "ଲ(ⓛ ω ⓛ)ଲ", "tags": ["animal", "cat", "menacing"] },
      { "emoji": "૮( ᵒ̌▱ᵒ̌ )ა", "tags": ["animal", "dog", "sad"] },
      { "emoji": "ദ്ദി( • O • )", "tags": ["animal", "koala", "cute"] },
      { "emoji": "(・(ᴥ)・)", "tags": ["animal", "bear", "face"] },
      { "emoji": "৲( °৺° )৴", "tags": ["animal", "jellyfish", "sea"] },
      { "emoji": "(￣(工)￣)", "tags": ["animal", "koala", "face"] },
      { "emoji": "<コ:彡", "tags": ["animal", "squid", "ika"] },
      { "emoji": "∈(・ω・)∋", "tags": ["animal", "sea creature", "clione"] },
      { "emoji": "(=；ェ；=)", "tags": ["crying cat", "animal", "sad"] },
      { "emoji": "/(. .)\\", "tags": ["spider", "animal", "insect"] },
      { "emoji": "∑(°)#))<<", "tags": ["hooked fish", "animal", "fishing"] },
      { "emoji": ">゜))彡", "tags": ["fish", "animal", "sea"] },
      { "emoji": "(・8・)", "tags": ["bird", "animal", "tweet"] },
      { "emoji": "～(￣、￣～)", "tags": ["worm", "slug", "animal"] },
      { "emoji": "＼(〇_ｏ)／", "tags": ["octopus", "animal", "sea"] },
      { "emoji": "∠( ´ ο ` )／", "tags": ["owl", "animal", "bird"] },
      { "emoji": "⊂((・⊥・))⊃", "tags": ["bat", "animal", "flying"] },
      { "emoji": "(^ V ^)", "tags": ["bunny", "rabbit", "animal"] },
      { "emoji": "くコ:彡", "tags": ["squid", "animal", "sea"] },
      { "emoji": "＼(・o・)／", "tags": ["monkey", "animal", "ape"] },
      { "emoji": "（`（●●）´）", "tags": ["pig", "animal", "boar"] }
    ]
  },
  {
    "name": "Actions",
    "kaomojis": [
      { "emoji": "_(._.)_", "tags": ["action", "bowing", "respect"] },
      { "emoji": "m(_ _)m", "tags": ["action", "bowing", "apology"] },
      { "emoji": "o/\\o", "tags": ["action", "high five", "cheer"] },
      { "emoji": "(ノ^_^)ノ", "tags": ["action", "hugging", "comfort"] },
      { "emoji": "d(^_^o)", "tags": ["action", "thumbs up", "good job"] },
      { "emoji": "ᕕ( ᐛ )ᕗ", "tags": ["action", "running", "fast"] },
      { "emoji": "ε=ε=┌( >_<)┘", "tags": ["action", "running away", "fleeing"] },
      { "emoji": "♪(┌・。・)┌", "tags": ["action", "dancing", "music"] },
      { "emoji": "＼(ﾟｰﾟ＼)", "tags": ["action", "dancing", "party"] },
      { "emoji": "φ(.. )", "tags": ["action", "writing", "studying"] },
      { "emoji": "(-_-) zzz", "tags": ["action", "sleeping", "tired"] },
      { "emoji": "( T_T)＼(^-^ )", "tags": ["action", "patting", "comforting"] },
      { "emoji": "┬─┬ノ( º _ ºノ)", "tags": ["action", "table unflip", "calm down"] },
      { "emoji": "(╯°Д°）╯︵ /(.□ . \\)", "tags": ["action", "flipping person", "angry"] },
      { "emoji": "＿〆(。。)", "tags": ["action", "writing", "note-taking"] },
      { "emoji": "_(:3 」∠)_", "tags": ["action", "lying down", "tired", "lazy"] },
      { "emoji": "(o・・o)/", "tags": ["action", "raising hand", "question"] },
      { "emoji": "ε=┌(；・∀・)┘", "tags": ["action", "running", "hurry"] },
      { "emoji": "_(┐「ε:)_", "tags": ["action", "lying down", "exhausted"] },
      { "emoji": "( ´-ω･)︻┻┳══━一", "tags": ["action", "sniper", "gun", "aiming"] },
      { "emoji": "-(_ -)", "tags": ["action", "hiding", "peeking"] },
      { "emoji": "[¬º-°]¬", "tags": ["action", "peeking", "watching"] },
      { "emoji": "(;・・)ノ", "tags": ["action", "pointing", "look"] },
      { "emoji": "/(ò.ó)┛", "tags": ["action", "pointing", "accusing"] },
      { "emoji": "(-ω-ゞ", "tags": ["action", "salute", "respect"] },
      { "emoji": "ヘ( ^o^)ノ＼(^_^ )", "tags": ["action", "high five", "teamwork"] },
      { "emoji": "(o_ _)o", "tags": ["action", "bowing", "deep bow"] },
      { "emoji": "(*´▽)っ)", "tags": ["action", "poking", "attention"] },
      { "emoji": "三( ε:)", "tags": ["action", "rolling", "tired"] },
      { "emoji": "~(＾◇^)/", "tags": ["action", "waving", "greeting"] },
      { "emoji": "(づ￣ ³￣)づ", "tags": ["hugging", "action", "love"] },
      { "emoji": "( ´･･)ﾉ(._.`)", "tags": ["comforting", "patting head", "action"] },
      { "emoji": "ଘ(੭*ˊᵕˋ)੭*", "tags": ["hugging", "action", "comfort"] }
    ]
  },
   {
    "name": "Special",
    "kaomojis": [
      { "emoji": "¯\\_(ツ)_/¯", "tags": ["special", "shrug", "don't know"] },
      { "emoji": "(⌐■_■)", "tags": ["special", "cool", "sunglasses"] },
      { "emoji": "（ ´∀｀）☆", "tags": ["special", "magic", "sparkle"] },
      { "emoji": "|д･)", "tags": ["special", "peeking", "hiding"] },
      { "emoji": "（ ´థ౪థ）", "tags": ["special", "creepy", "smirk"] },
      { "emoji": "【( G e G )】", "tags": ["special", "robot", "glasses"] },
      { "emoji": "（・⊝・）", "tags": ["special", "bird", "beak"] },
      { "emoji": "(´・(oo)・｀)", "tags": ["special", "pig", "animal"] },
      { "emoji": "ᕙ(⇀‸↼‶)ᕗ", "tags": ["special", "flexing", "strong"] },
      { "emoji": "（ミ￣ー￣ミ）", "tags": ["special", "smug", "cat"] },
      { "emoji": "(^=◕ᴥ◕=^)", "tags": ["special", "cat", "cute"] },
      { "emoji": "°˖✧◝(⁰▿⁰)◜✧˖°", "tags": ["special", "sparkly", "excited"] },
      { "emoji": "ヽ(⌐■_■)ノ♪♬", "tags": ["special", "dancing", "cool"] },
      { "emoji": "Z( ‘́⌣’̀ )", "tags": ["special", "zombie", "creepy"] },
      { "emoji": "~(⊕⌢⊕)~", "tags": ["special", "alien", "ufo"] },
      { "emoji": "( ఠ ͟ʖ ఠ)", "tags": ["special", "lenny face", "smirk"] },
      { "emoji": "[̲̅$̲̅(̲̅ιο̲̅̅)̲̅$̲̅]", "tags": ["special", "money", "rich"] },
      { "emoji": "┬┴┬┴┤(･_├┬┴┬┴", "tags": ["special", "peeking", "hiding"] },
      { "emoji": "（ つ Д ｀）", "tags": ["special", "crying", "emotional"] },
      { "emoji": "( •̀ ω •́ )y", "tags": ["special", "determined", "fighting"] },
      { "emoji": "〆(・∀・＠)", "tags": ["special", "writing email", "typing"] },
      { "emoji": "(बिद)", "tags": ["special", "mustache", "fancy"] },
      { "emoji": "~( -_ -)~", "tags": ["special", "whatever", "indifferent"] },
      { "emoji": "((((((((((ﾉ∀`)･ﾟ･｡", "tags": ["special", "running and crying", "fleeing"] },
      { "emoji": "┣¨┣¨┣¨┣¨┣¨", "tags": ["special", "menacing", "sound effect", "jojo"] },
      { "emoji": "ゴゴゴゴ", "tags": ["special", "menacing", "sound effect", "jojo"] },
      { "emoji": "(-(-_(-_-)_-)-)", "tags": ["special", "ghosts", "spooky"] },
      { "emoji": "†_(`O´)_†", "tags": ["special", "angel", "heavenly"] },
      { "emoji": "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", "tags": ["special", "magic", "sparkles", "excited"] },
      { "emoji": "༼ つ ◕_◕ ༽つ", "tags": ["special", "give", "summoning", "hugging"] },
      { "emoji": "⤜(ⱺ ʖ̯ⱺ)⤏", "tags": ["lenny face", "special", "look"] },
      { "emoji": "୧(﹒︠益﹒︡)୨", "tags": ["angry", "flexing", "special"] },
      { "emoji": "╲⎝⧹ ( ͡° ͜ʖ ͡°) ⎠╱", "tags": ["lenny face", "spider", "special"] }
    ]
  },
  {
    "name": "Surprised",
    "kaomojis": [
      { "emoji": "(o_O)", "tags": ["surprised", "shocked", "uh oh"] },
      { "emoji": "(O_o)", "tags": ["surprised", "shocked", "confused"] },
      { "emoji": "(⊙_⊙)", "tags": ["surprised", "staring", "shocked"] },
      { "emoji": "Σ(°ロ°)", "tags": ["surprised", "omg", "shocked"] },
      { "emoji": "(ﾉﾟ0ﾟ)ﾉ~", "tags": ["surprised", "amazed", "wow"] },
      { "emoji": "(」°ﾛ°)｣", "tags": ["surprised", "yelling", "shocked"] },
      { "emoji": "Σ(ﾟДﾟ)", "tags": ["surprised", "shocked", "startled"] },
      { "emoji": "w(°ｏ°)w", "tags": ["surprised", "wow", "amazed"] },
      { "emoji": "＼(°o°)／", "tags": ["surprised", "shocked", "oh my"] },
      { "emoji": "(°Д°)", "tags": ["surprised", "shocked", "agape"] },
      { "emoji": "щ(ºДºщ)", "tags": ["surprised", "shocked", "desperate"] },
      { "emoji": "( °o°)", "tags": ["surprised", "wow", "shocked"] },
      { "emoji": "Σ(･口･)", "tags": ["surprised", "shocked", "speechless"] },
      { "emoji": "( º o º )", "tags": ["surprised", "wow", "amazed"] },
      { "emoji": "ヽ(ﾟДﾟ)ﾉ", "tags": ["surprised", "shocked", "omg"] },
      { "emoji": "(⊙_⊙;)", "tags": ["surprised", "sweating", "nervous"] },
      { "emoji": "∑(O_O;)", "tags": ["shocked", "sweating", "nervous"] },
      { "emoji": "Σ(･ω･ﾉ)ﾉ", "tags": ["surprised", "hands up", "startled"] },
      { "emoji": "!?(･_･;?", "tags": ["surprised", "confused", "questioning"] },
      { "emoji": "(*ﾟﾛﾟ)", "tags": ["surprised", "shocked", "gasp"] },
      { "emoji": "（・□・；）", "tags": ["surprised", "nervous", "shocked"] },
      { "emoji": "(⚆_⚆)", "tags": ["surprised", "staring", "shocked"] },
      { "emoji": "(꒪ཫ꒪;)", "tags": ["shocked", "dying", "surprised"] },
      { "emoji": "｢(ﾟﾍﾟ)", "tags": ["surprised", "confused", "questioning"] }
    ]
  },
  {
    "name": "Shy",
    "kaomojis": [
      { "emoji": "(* /ω＼*)", "tags": ["shy", "embarrassed", "blushing"] },
      { "emoji": "(⁄ ⁄•⁄ω⁄•⁄ ⁄)", "tags": ["shy", "blushing", "flustered"] },
      { "emoji": "(/ω＼)", "tags": ["shy", "peeking", "embarrassed"] },
      { "emoji": "(〃ω〃)", "tags": ["shy", "embarrassed", "blushing"] },
      { "emoji": "(*ﾉωﾉ)", "tags": ["shy", "embarrassed", "hiding face"] },
      { "emoji": "(//ω//)", "tags": ["shy", "blushing", "embarrassed"] },
      { "emoji": "(´,,•ω•,,`)", "tags": ["shy", "blushing", "cute"] },
      { "emoji": "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)", "tags": ["shy", "embarrassed", "cute"] },
      { "emoji": "|ω・`）", "tags": ["shy", "peeking", "looking"] },
      { "emoji": "ドキドキ", "tags": ["shy", "heartbeat", "nervous", "dokidoki"] },
      { "emoji": "(⁄ ⁄•⁄-⁄•⁄ ⁄)", "tags": ["blushing", "shy", "flustered"] },
      { "emoji": "(⁄ ⁄.⁄ ⁄)", "tags": ["blushing", "shy", "embarrassed"] },
      { "emoji": "_:(´ཀ`」 ∠):_", "tags": ["dying from embarrassment", "shy", "overwhelmed"] },
      { "emoji": "(｡>﹏<｡)", "tags": ["shy", "flustered", "embarrassed"] },
      { "emoji": "(ง ื▿ ื)ว", "tags": ["shy", "cute", "bashful"] },
      { "emoji": "羞羞", "tags": ["shy", "bashful", "text"] },
      { "emoji": "(*/_＼*)", "tags": ["hiding face", "shy", "embarrassed"] },
      { "emoji": "(⌒_⌒;)", "tags": ["shy", "awkward smile", "nervous"] },
      { "emoji": "|д･)ﾉ", "tags": ["peeking out", "shy", "greeting"] },
      { "emoji": "(｡･･｡)", "tags": ["shy", "quiet", "bashful"] },
      { "emoji": "(〃▽〃)", "tags": ["shy", "blushing", "embarrassed"] },
      { "emoji": "…(｡>ㅅ<｡)…", "tags": ["shy", "flustered", "nervous"] },
      { "emoji": "(/_＼)", "tags": ["shy", "peeking", "embarrassed"] }
    ]
  },
  {
    "name": "Reactions",
    "kaomojis": [
      { "emoji": "(´･_･`)", "tags": ["reaction", "confused", "speechless"] },
      { "emoji": "(・・?)", "tags": ["reaction", "confused", "questioning"] },
      { "emoji": "┐(￣ヘ￣)┌", "tags": ["reaction", "shrug", "don't know"] },
      { "emoji": "(－‸ლ)", "tags": ["reaction", "facepalm", "disappointed"] },
      { "emoji": "( ﾟдﾟ)", "tags": ["reaction", "realization", "what"] },
      { "emoji": "╭( ๐_๐)╮", "tags": ["reaction", "confused", "what"] },
      { "emoji": "(•_•)", "tags": ["reaction", "stare", "serious"] },
      { "emoji": "(^～^;)", "tags": ["reaction", "awkward", "sweating"] },
      { "emoji": "(¬_¬)", "tags": ["reaction", "disapproval", "skeptical"] },
      { "emoji": "(；￣Д￣)", "tags": ["reaction", "what", "confused"] },
      { "emoji": "(´-`).｡oO( ... )", "tags": ["reaction", "thinking", "musing"] },
      { "emoji": "(´～｀)", "tags": ["reaction", "thinking", "hmm"] },
      { "emoji": "( ´_ゝ`)", "tags": ["reaction", "smug", "indifferent", "heh"] },
      { "emoji": "y( ꒪Д꒪)y", "tags": ["reaction", "what the", "shocked"] },
      { "emoji": "(•ิ_•ิ)?", "tags": ["reaction", "questioning", "huh", "curious"] },
      { "emoji": "(☞ﾟ∀ﾟ)☞", "tags": ["reaction", "pointing", "you got it", "this"] },
      { "emoji": "(ಠ_ಠ)", "tags": ["reaction", "disapproval", "stare"] },
      { "emoji": "乁( ⁰͡ Ĺ̯ ⁰͡ ) ㄏ", "tags": ["reaction", "fancy shrug", "don't know"] },
      { "emoji": "(；⌣̀_⌣́)", "tags": ["reaction", "trying to hold it together", "enduring"] },
      { "emoji": "(´・ω・)っ", "tags": ["reaction", "here you go", "offering"] },
      { "emoji": "(ﾟ⊿ﾟ)", "tags": ["reaction", "spitting", "disgusted"] },
      { "emoji": "(~˘▾˘)~", "tags": ["dancing", "reaction", "silly"] },
      { "emoji": "(⊙x⊙;)", "tags": ["dizzy", "confused", "reaction"] },
      { "emoji": "(」・ω・)」", "tags": ["cheering", "dancing", "reaction"] }
    ]
  },
  {
    "name": "Weird & Funny",
    "kaomojis": [
      { "emoji": "(☞ ͡° ͜ʖ ͡°)☞", "tags": ["funny", "weird", "lenny face", "pointing"] },
      { "emoji": "༼ ಠل͟ಠ༽", "tags": ["funny", "weird", "lenny face", "mustache"] },
      { "emoji": "（╯°□°）╯︵( .o.)", "tags": ["funny", "flipping", "rage", "person"] },
      { "emoji": "(づ｡◕‿‿◕｡)づ", "tags": ["funny", "weird", "hug", "creepy"] },
      { "emoji": "＼(｀0´)／", "tags": ["funny", "yelling", "dramatic"] },
      { "emoji": "(._.) ( l: ) ( .-. ) ( :l ) (._.)", "tags": ["funny", "rolling", "bored"] },
      { "emoji": "（ ´☣///_ゝ///☣｀）", "tags": ["funny", "weird", "creepy", "blushing"] },
      { "emoji": "s(・｀ヘ´・;)ゞ", "tags": ["funny", "salute", "serious", "military"] },
      { "emoji": "ヾ( ͝° ͜ʖ͡°)ノ♪", "tags": ["funny", "lenny face", "dancing"] },
      { "emoji": "~(˘▾˘~) (~˘▾˘)~", "tags": ["funny", "dancing", "silly"] },
      { "emoji": "ε=(~￣▽￣)~", "tags": ["funny", "relaxed", "content"] },
      { "emoji": "へ(゜∇、°)へ", "tags": ["funny", "weird", "creepy", "drooling"] },
      { "emoji": "⊂(・(ェ)・)⊃", "tags": ["funny", "bear hug", "animal"] },
      { "emoji": "(╯ຈل͜ຈ)╯︵ ┻━┻", "tags": ["funny", "table flip", "lenny face"] },
      { "emoji": "(／･ω･)／≡≡≡≡((((☆", "tags": ["funny", "punch", "action", "comet"] },
      { "emoji": "(⌐□_□) DEAL WITH IT", "tags": ["funny", "deal with it", "sunglasses"] },
      { "emoji": "(ι´Д｀)ﾉ", "tags": ["funny", "tired", "waving"] },
      { "emoji": "(∩` ﾛ ´)⊃━炎炎炎炎炎", "tags": ["funny", "magic", "fireball", "spell"] },
      { "emoji": "ヽ(๏∀๏ )ﾉ", "tags": ["funny", "crazy", "excited"] },
      { "emoji": "（（（（( ´Д｀)ﾉ", "tags": ["funny", "running away", "fleeing"] },
      { "emoji": "（＾ｖ＾）", "tags": ["happy", "smile", "funny face"] }
    ]
  }
];